name: "actions"

on:
  pull_request:
  workflow_dispatch:

jobs:
  hello-docker-workflow-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          args: "Mona the Octocat"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"



      

