name: "HelloDocker"

on:
  pull_request:
  workflow_dispatch:

jobs:
  hello-docker-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/hellodocker.yml
        id: hellou
        with:
          who-to-greet: "Mona the Octocat"
      - run: |
          echo "The time was ${{ steps.hellou.outputs.time }}"
          echo $HELLO

      

