name: "HelloDocker"

on:
  pull_request:
  workflow_dispatch:

jobs:
  hello-docker-workflow-job:
    uses: ./.github/workflows/hellodocker.yml@main
    with:
        who-to-greet: "Mona the Octocat"


      

