name: "HelloDocker"
on:
  workflow_call:
    inputs:
      who-to-greet: # id of input
        description: 'Who to greet'
        required: true
        default: 'Person'
    outputs:
      time: # id of output
        description: 'The time we greeted you'
    runs:
        using: "docker"
        image: "Dockerfile"
        args:
            - ${{ inputs.who-to-greet }}
jobs:
  reusable-hellodocker-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The time was ${{ outputs.time }}"
          echo $HELLO